### PR TITLE
Bump CCCL version to include cuda::std::span fix

### PR DESCRIPTION
**Pull request by sleeepyjack**
## Description
This PR updates the CCCL version to include a fix for `cuda::std::span` which is required for cuCollections to work properly with CCCL 2.5.0. 

Most of the changes between the last CCCL version bump (#607) and this one were related to doc updates and unit test fixes, so I don't expect much functional impact for RAPIDS.

After this PR we likely have to bump the cuco version again to include the new changes.

### CCCL PR:

- NVIDIA/cccl#1836

### CUCO PR:

- NVIDIA/cuCollections#502

### RAPIDS PRs:

- [x] rapidsai/cudf#15986
  - [error during docs-build](https://github.com/rapidsai/cudf/actions/runs/9406273871/job/25911619452?pr=15946#step:9:2243) but seems unrelated
- [x] rapidsai/cugraph#4483
  - some CI jobs ran into a network timeout -> rerunning
- [x] rapidsai/cuml#5924
  - successful apart from some optional conda python tests
- [x] rapidsai/raft#2358
  - This one is weird as it [shows an error](https://github.com/rapidsai/raft/actions/runs/9475150045/job/26109283214?pr=2358#step:7:824) that is similar to the one we found in cuco when bumping the CCCL version to 2.5.0. However, we thought the problem was on cuco's end and pushed a fix that resolved the issue (see [Slack thread](https://nvidia.slack.com/archives/CCP05T27R/p1718060955876199))
- [x] rapidsai/rmm#1584

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by bdice** [comment]
The diff is here: https://github.com/NVIDIA/cccl/compare/fde1cf79bde6744b6739636f502b5edfefe302e1...e21d607157218540cd7c45461213fb96adf720b7

I feel confident in merging this as soon as you think it's sufficiently tested @sleeepyjack @PointKernel. All of the commits up to those from yesterday (which unfortunately includes the fix you need) were tested by the latest run of https://github.com/NVIDIA/cccl/pull/1667.

**Comment by PointKernel** [comment]
Added `rmm` PR as well: https://github.com/rapidsai/rmm/pull/1584

**Comment by sleeepyjack** [comment]
cugraph CI has some problems. I restarted it one more time. Fingers crossed. Apart from that all other projects seem to be fine with the change.

**Comment by sleeepyjack** [comment]
cugraph now finally also paases all unit tests. What's going on with the failing rapids-cmake tests? I can't make sense of them.

**Comment by sleeepyjack** [comment]
All problems have been resolved. This PR is ready for review.

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
Thanks @sleeepyjack!

**Pull request merged**
