### PR TITLE
Docs: RAPIDS.cmake should be placed in current bin dir

### LINKED ISSUE #240: [BUG] Problems with default recipe and dependent projects using RAPIDS.cmake
**Describe the bug**
If a dependent project also uses `RAPIDS.cmake`, the default recipe will download and overwrite the file in the root build directory. This is especially problematic if the dependent project downloads an *older* version of `rapids-cmake`, pulling in an older `versions.json`.

**Steps/Code to reproduce bug**
Configure and build https://github.com/NVIDIA/cuCollections; it should work. Then re-run `cmake .` and observe that older versions of `libcudacxx` and `Thrust` are added (based on what https://github.com/NVIDIA/nvbench pulls in). The build will fail afterwards because cuCollections requires the newer versions.

**Expected behavior**
The build should be stable and work after reconfiguration.

### PR DESCRIPTION
**Pull request by robertmaynard**
Instead of placing in the root level binary directory place it in the current binary dir to avoid clobbering an existing RAPIDS.cmake

Fixes #240

### CODE REVIEW

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
Just noticed the `DO NOT MERGE` label. This PR looks fine to me but I may be unaware of some missing piece of this.

**Comment by robertmaynard** [comment]
> Just noticed the `DO NOT MERGE` label. This PR looks fine to me but I may be unaware of some missing piece of this.

Updated the examples to include guards around downloading the file if it already exists, which we also want to make sure we don't keep downloading the file.

**Review by bdice — APPROVED** [review]
LGTM!

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
