### PR TITLE
Add CMake intersphinx support

### PR DESCRIPTION
**Pull request by bdice**
This PR provides basic intersphinx functionality for the rapids-cmake docs to begin addressing #141. I updated one page (`docs/dependency_tracking.rst`) to use intersphinx links. No other pages have been updated to use intersphinx yet. Reviewers, please let me know if this is a helpful start -- and feel free to push directly to this branch if you'd like to work on other pages. I just wanted to get a working example started.

### CODE REVIEW

**Review by robertmaynard — APPROVED** [review]
This is geat! 

Tested locally and everything works as expected

**Comment by bdice** [comment]
@robertmaynard Ready to merge? Go for it if so. Just wanted to double-check since I merged your changes into this PR.

**Comment by robertmaynard** [comment]
> @robertmaynard Ready to merge? Go for it if so. Just wanted to double-check since I merged your changes into this PR.

Lets target 22.04 for these changes. That will give us time to update all the documentation to cross site link correctly.

**Comment by bdice** [comment]
Target branch updated to 22.04.

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
