### PR TITLE
Mark flaky test as serial

### PR DESCRIPTION
**Pull request by vyasr**
## Description

This test may be running into issues with the multi-config generator running in parallel.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by vyasr** [comment]
See failures like: https://github.com/rapidsai/rapids-cmake/actions/runs/7200469665/job/19614692993

**Review by robertmaynard — APPROVED** [review]

**Comment by vyasr** [comment]
I've rerun CI three times now. If this last run succeeds I'm happy to call the problem solved for now.

**Review by bdice — APPROVED** [review]
Ah! Thanks for this. I have noticed this at least once before.

**Pull request merged**
