### PR TITLE
Fix message context

### LINKED ISSUE #514: [BUG] `rapids_cython_init()` does not clear its modification to `CMAKE_MESSAGE_CONTEXT`
There is no matching `list(POP_BACK CMAKE_MESSAGE_CONTEXT)` for https://github.com/rapidsai/rapids-cmake/blob/branch-24.02/rapids-cmake/cython/init.cmake#L40. Since `rapids_cython_init()` is a macro, this doesn't reset on scope-exit.

### PR DESCRIPTION
**Pull request by vyasr**
## Description

Resolves #514 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Review by KyleFromNVIDIA — APPROVED** [review]
+1

I wonder if there would be a way to test this to make sure future macros don't have this problem...

**Comment by vyasr** [comment]
That's a good question. I'm not sure if there's an easy, semantically-aware solution. The simplest purely textual solution I could think of would be writing a pre-commit hook that just counts instances of the insertion and pop_back. There's probably an ideal middle ground that we could find.

**Comment by robertmaynard** [comment]
> That's a good question. I'm not sure if there's an easy, semantically-aware solution. The simplest purely textual solution I could think of would be writing a pre-commit hook that just counts instances of the insertion and pop_back. There's probably an ideal middle ground that we could find.

I can't think of a nice way that doesn't include parsing the source code.

**Pull request merged**
