### PR TITLE
Add workaround for gcc bug in cuco

### PR DESCRIPTION
**Pull request by miscco**
We discovered an unfortunate bug in the gcc constexpr evaluator that broke the alignment calculations in cuco.

There is a simple workaround so employ that to unbreak rapids with cccl ToT

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
Is there a reason to use a patch and not to update cuCollections and then update the SHA in versions.json?

**Review by bdice — APPROVED** [review]
Style check requires a trailing newline in the file. Otherwise LGTM.

**Comment by bdice** [comment]
@miscco asked me offline about the testing procedure we need for this PR. I pointed to the downstream CI testing we typically do here: https://github.com/rapidsai/rapids-cmake/pull/677#issuecomment-2294110382

Here is the comparison between the previous and new commits of cuCollections: https://github.com/NVIDIA/cuCollections/compare/abc5095b011feccd7d3ecb36b369741b96ae6f0e..d3477661d771e0d6fd22259bf6dd6f8c64a7401c

The diff is pretty small and confined, so I would be okay merging this PR without downstream CI testing if it saves time. @miscco verified that cuDF builds with this change. But I'd want to get an okay from @PointKernel and/or @robertmaynard before merging.

**Comment by PointKernel** [comment]
Thanks for bringing this up.

I reviewed the changes yesterday, and as @bdice mentioned, they are minimal. I don't see any need to retest the RAPIDS suite for such a minor update.

**Review by PointKernel — APPROVED** [review]

**Comment by robertmaynard** [comment]
Will merge early tomorrow :+1:

**Pull request merged**
