### PR TITLE
Remove usage of FetchContent from tests to improve perf

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Improve performance of rapids-cmake tests in CI by removing the usage of fetch content, and instead
using symlinks and tricking fetch content that it was used to get rapids-cmake.

This reduces the size of each test in the binary directory as they no longer have a copy of rapids-cmake. Plus still works
for tests that fetch rapids-cmake indirectly ( via cpm due to testing projects like rmm ). 

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.

### CODE REVIEW

**Comment by ajschmidt8** [comment]
> Were tests particularly slow before? This PR seems like it introduces more boilerplate to speed up something that didn't appear to be a bottleneck, but I may have just been unaware of it. The new approach seems like a cleaner handling of local changes, though, which is a definite improvement over the old copying approach.

This PR was originally created in an attempt to resolve the issue described in the comment below. It turns out these changes were not the cause of the problem.

- https://github.com/rapidsai/rapids-cmake/pull/301#issuecomment-1315635528

**Comment by robertmaynard** [comment]
While we found that `sccache` was causing the worst of slow-downs, this does solves a problem with rapids-cmake tests.

In general the inital configure of each test will include a full git clone of the local copy of rapids-cmake. Depending on the file-system, and size of the `.git` folder you can see a significant cost. I know locally I had to delete my src directory since initial configures of tests was taking ~20sec.

In testing locally with a freshly cloned rapids-cmake I see this shaving ~2sec from each test, which is really nice when most tests only take ~4-6sec.

**Review by vyasr — APPROVED** [review]

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
