### PR TITLE
Correctly set the install location for nvcomp when using the proprietary binary

### PR DESCRIPTION
**Pull request by vyasr**
## Description

When we download the nvcomp binaries, we have to ensure that those binaries are also using the location determined by `rapids_cmake_install_lib_dir`.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by robertmaynard** [comment]
Changes look correct to me.

**Review by msarahan — APPROVED** [review]

**Comment by vyasr** [comment]
We've now confirmed that this fix works on https://github.com/rapidsai/cudf/pull/15483. However, it looks like it's incomplete. The cmake files that the nvcomp package contains include the `lib` directory, but since we've patched it to be `lib64` (in cases where that's what `rapids_cmake_install_lib_dir` returns) the cmake is now incorrect. I think we'll have to do a manual modification of the `nvcomp-release-targets.cmake` file to replace `${_IMPORT_PREFIX}/lib/` with `${_IMPORT_PREFIX}/${lib_dir}/`. @robertmaynard does this seem too hacky to you?

**Comment by robertmaynard** [comment]
> We've now confirmed that this fix works on [rapidsai/cudf#15483](https://github.com/rapidsai/cudf/pull/15483). However, it looks like it's incomplete. The cmake files that the nvcomp package contains include the `lib` directory, but since we've patched it to be `lib64` (in cases where that's what `rapids_cmake_install_lib_dir` returns) the cmake is now incorrect. I think we'll have to do a manual modification of the `nvcomp-release-targets.cmake` file to replace `${_IMPORT_PREFIX}/lib/` with `${_IMPORT_PREFIX}/${lib_dir}/`. @robertmaynard does this seem too hacky to you?

Looks required for us to have a consistent install location when doing pip packages. So we will need to do it.
I would like to see the logic be placed in someplace like `cmake/detail` so that we can re-use it when needed

**Comment by vyasr** [comment]
I've pushed out something that I think will work. Once I see it working with the cudf PR, I'll try and pull it out into a more generalized utility. @robertmaynard any suggestions on what you would want that to look like?

**Comment by vyasr** [comment]
The Python wheel builds in the cudf repo worked, so I think this is functionally ready! So I just need to address Robert's request above.

**Comment by robertmaynard** [comment]
> I've pushed out something that I think will work. Once I see it working with the cudf PR, I'll try and pull it out into a more generalized utility. @robertmaynard any suggestions on what you would want that to look like?

We should have a test that verifies that transformation has occurred.

**Review by robertmaynard — APPROVED** [review]

**Pull request merged**
