### PR TITLE
remove setup.cfg, use pyproject.toml

### PR DESCRIPTION
**Pull request by jameslamb**
## Description

This repo doesn't have a Python package or use `setuptools`, but it has a `setup.cfg`... to hold configuration for tools like `codespell`.

This proposes removing that and using a `pyproject.toml` to store that configuration, matching the conventions used across most of the rest of RAPIDS.

It also updates pre-commit configurations to use the latest version of `rapids-dependency-file-generator` (v1.17.0).

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Review by bdice — COMMENTED** [review]
We might need some pre-commit fixes for this repo. I realized in https://github.com/rapidsai/rmm/pull/1769 that we didn't have codespell set up correctly for RMM.

I'll see if I can push a change and then approve this.

**Comment by bdice** [comment]
I applied the fix and it caught an issue with the config. I think the skip files needed to be wrapped in quotes or something. Also we don't need to ignore `.github` -- we aren't doing that in rmm, at least, and there are no typos, so I think it's fine to keep it included.

**Comment by jameslamb** [comment]
Ah great, thank you for fixing that! I didn't realize `codespell` didn't look for `pyproject.toml` by default.

**Pull request merged**
