### PR TITLE
Update to CPM v0.38.5

### PR DESCRIPTION
**Pull request by trxcllnt**
## Description
Update to CPM [v0.38.5](https://github.com/cpm-cmake/CPM.cmake/releases/tag/v0.38.5).

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [x] I have added new files under rapids-cmake/
   - [x] I have added include guards (`include_guard(GLOBAL)`)
   - [x] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by robertmaynard** [comment]
Unless we absolutely need this for 23.10 lets merge this first for 23.12 so we have lots of time to find and fix issues

**Comment by trxcllnt** [comment]
@robertmaynard CPM v0.38 is the one that added support for `add_subdirectory(... [SYSTEM])`, which is the feature that motivated this particular PR. Is upgrading CPM really that risky?

**Comment by robertmaynard** [comment]
I didn't know if this was a simple version bump to keep up to date, or for new features.
Since we have a need for `add_subdirectory(SYSTEM)` I am good with adding this to 23.10

**Pull request merged**
