### PR TITLE
Update cuco git tag

### PR DESCRIPTION
**Pull request by PointKernel**
Related to https://github.com/rapidsai/cudf/issues/12108.

This PR fetches the latest cuCo git tag to fix a bug of iterator range overflows.
 
## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by PointKernel** [comment]
I can change the base branch to `22.12` if it's a hot fix.

cc @abellina

**Comment by PointKernel** [comment]
Targeting 22.12 based on offline discussion.

**Review by bdice — APPROVED** [review]
Here's the diff: https://github.com/NVIDIA/cuCollections/compare/1e3c5842c6e212e0bd7de9802af583e53009f4a6..2a194c9831324904120113bc18135e7933369ee8

It looks good to me!

**Comment by robertmaynard** [comment]
@PointKernel @bdice we ready to merge this?

**Comment by PointKernel** [comment]
> @PointKernel @bdice we ready to merge this?

Yes, please. I don't have write access to this repo.

**Comment by bdice** [comment]
@gpucibot merge

**Pull request merged**
