### PR TITLE
Fetch the latest cuco and remove outdated patches

### PR DESCRIPTION
**Pull request by PointKernel**
## Description
This PR bumps to the latest cuco version which removes experimental namespace and includes multiple bug fixes.

CI must pass on these PRs before we can merge this change:
- [ ] https://github.com/rapidsai/cudf/pull/14849
- [ ] https://github.com/rapidsai/cugraph/pull/4111
- [ ] https://github.com/rapidsai/raft/pull/2118

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by PointKernel** [comment]
This version bump includes multiple breaking changes in cuco. We want to make sure the downstream `cudf`, `cugraph` and `raft` PRs are ready to merge before merging this PR.

**Review by robertmaynard — APPROVED** [review]

**Review by bdice — APPROVED** [review]

**Comment by PointKernel** [comment]
@robertmaynard This is ready to merge. Thanks!

**Pull request merged**
