### PR TITLE
Update libcudacxx to 2.1.0

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR separates out the libcudacxx update from #399. I am proposing to update only libcudacxx to 2.1.0, and leave thrust/cub pinned at 1.17.2 until all of RAPIDS is ready to update. Then we can move forward with #399 next.

Separating the update for libcudacxx should allow RAPIDS to use some of the new features we want while giving more time to RAPIDS libraries to migrate to CCCL 2.1.0 (particularly for breaking changes in Thrust/CUB).

**Immediate benefits of bumping only libcudacxx to 2.1.0:**
- Enables migration to Thrust/CUB 2.1.0 to be done more incrementally, because we could merge PRs using `cuda::proclaim_return_type` into cudf/etc. which would reduce the amount of unmerged code we're maintaining in the "testing PRs" while waiting for all RAPIDS repos to be ready for Thrust/CUB 2.1.0.
- Unblocks work in rmm (https://github.com/rapidsai/rmm/pull/1095) and quite a few planned changes for cuCollections (such as https://github.com/NVIDIA/cuCollections/issues/332, https://github.com/NVIDIA/cuCollections/issues/331, https://github.com/NVIDIA/cuCollections/issues/289)

**Risk Assessment:**
This should be fairly low risk because libcudacxx 2.1.0 is similar to our current pinning of 1.9.1 -- the major version bump was meant to align with Thrust/CUB and isn't indicative of major breaking changes.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by bdice** [comment]
Tracking CI pass/fail in these PRs:
- [x] https://github.com/rapidsai/rmm/pull/1361
- [ ] https://github.com/rapidsai/cudf/pull/14286
- [ ] https://github.com/rapidsai/raft/pull/1902
- [ ] https://github.com/rapidsai/cuspatial/pull/1286
- [ ] https://github.com/rapidsai/cugraph/pull/3937

I think it should be sufficient if these pass, since these are the only RAPIDS repos that explicitly use `#include <cuda/...>`. There's no internal use of libcudacxx in Thrust/CUB until we update Thrust/CUB as well, so I think it's isolated to RAPIDS libraries' own use of libcudacxx.

**Comment by bdice** [comment]
cuSpatial is a bit tricky to test with an updated libcudacxx package unless I build it locally from source. I am going to attempt that tomorrow to verify, but overall I expect the risk of breaking builds by updating libcudacxx to 2.1.0 is very low.

**Comment by bdice** [comment]
I verified that cuSpatial builds locally. This PR should be ready to review and merge.

**Review by robertmaynard — APPROVED** [review]

**Comment by miscco** [comment]
That is amazing, thanks a lot for pushing this through

**Pull request merged**
