### PR TITLE
Update to nvcomp 2.4 which now offers aarch64 binaries!

### PR DESCRIPTION
**Pull request by robertmaynard**

### CODE REVIEW

**Comment by vyasr** [comment]
@vuule yes, create a PR like https://github.com/rapidsai/cudf/pull/11327 pointing to this rapids-cmake branch.

**Comment by vuule** [comment]
Opened https://github.com/rapidsai/cudf/pull/11739

**Comment by vuule** [comment]
> rapidsai/cudf#11739

CI passed, this PR should be GTG.

**Review by vuule — APPROVED** [review]

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
