### PR TITLE
Fix `nvtx3` build export

### PR DESCRIPTION
**Pull request by trxcllnt**
## Description

Fixes the following error:

```
CMake Error at /home/coder/rmm/build/conda/cuda-12.2/latest/rmm-targets.cmake:52 (set_target_properties):
  The link interface of target "rmm::rmm" contains:
    nvtx::nvtx3-cpp
  but the target was not found.  Possible reasons include:
    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
Call Stack (most recent call first):
  /home/coder/rmm/build/conda/cuda-12.2/latest/rmm-config.cmake:75 (include)
  build/conda/cuda-12.2/release/cmake/CPM_0.38.5.cmake:243 (find_package)
  build/conda/cuda-12.2/release/cmake/CPM_0.38.5.cmake:303 (cpm_find_package)
  build/conda/cuda-12.2/release/_deps/rapids-cmake-src/rapids-cmake/cpm/find.cmake:189 (CPMFindPackage)
  build/conda/cuda-12.2/release/_deps/rapids-cmake-src/rapids-cmake/cpm/rmm.cmake:75 (rapids_cpm_find)
  cmake/thirdparty/get_rmm.cmake:20 (rapids_cpm_rmm)
  cmake/thirdparty/get_rmm.cmake:24 (find_and_configure_rmm)
  CMakeLists.txt:192 (include)
```

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by trxcllnt** [comment]
I noticed [we do this in RMM for spdlog](https://github.com/rapidsai/rmm/blob/4e9482f5a7473dd8b960f76c9c399576c9662ae3/cmake/thirdparty/get_spdlog.cmake#L20-L31), so maybe we should do that in `rapids-cmake/cpm/spdlog.cmake` instead?

**Comment by robertmaynard** [comment]
> I noticed [we do this in RMM for spdlog](https://github.com/rapidsai/rmm/blob/4e9482f5a7473dd8b960f76c9c399576c9662ae3/cmake/thirdparty/get_spdlog.cmake#L20-L31), so maybe we should do that in `rapids-cmake/cpm/spdlog.cmake` instead?

There is an open issue to track that refactoring. https://github.com/rapidsai/rapids-cmake/pull/592 started down that path as part of the update to a newer spdlog version.

**Comment by robertmaynard** [comment]
@trxcllnt I updated the PR to consistently use the name `nvtx3` instead of `NVTX3`. Doing so makes the package logic consistent , and removes the need to do `rapids_export_package(BUILD nvtx3 ${_RAPIDS_BUILD_EXPORT_SET} GLOBAL_TARGETS nvtx3-c nvtx3-cpp)` as that is now properly done by `rapids_cpm_find` since it is given the corrected name.

Tested with a local rmm build tree and I see rmm the correct usage of the nvtx3 package in the rmm build tree.

**Review by robertmaynard — APPROVED** [review]

**Pull request merged**
