### PR TITLE
Introduce clang-format to rapids-cmake to format C++ code examples

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
In preparation of more C++ code being added to rapids-cmake introduce a .clang-format file to the project to keep everything with a consistent style and formatting.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.

### CODE REVIEW

**Review by vyasr — COMMENTED** [review]
How did you choose the settings? Are they copied from another project?

I was going to recommend adding a pre-commit hook, but it looks like we've already got one. Have we been running it without a format file?

**Comment by robertmaynard** [comment]
I copied the format file from cudf. 

Yeah we have been running format without any file so it was using the defaults. But I don't think we ever ran it over the existing c++ files

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
Thanks! This simplifies #328.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
