### PR TITLE
Update cuco git tag to fetch bug fixes and cleanups

### PR DESCRIPTION
**Pull request by PointKernel**
This PR fetches the latest changes in cuco to:

- Inline `cuco::sentinel` namespace (https://github.com/NVIDIA/cuCollections/pull/247)
- Fix memory leak in `static_map::retrieve_all` (https://github.com/NVIDIA/cuCollections/pull/257)
- Use public `cuco::murmurhash3_32` (https://github.com/NVIDIA/cuCollections/pull/253)

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by robertmaynard** [comment]
It would be great to open a PR for cudf to verify that bumping cuCollection will  have no side-effects.

**Review by robertmaynard — APPROVED** [review]

**Comment by robertmaynard** [comment]
Is ready to merge as the libcudf PR passes

**Comment by PointKernel** [comment]
> Is ready to merge as the libcudf PR passes

Thanks! I'm closing the cudf PR.

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
