### PR TITLE
Move to latest nvbench which has nvml+static support

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
With https://github.com/NVIDIA/nvbench/pull/148 being merged we can drop our custom patch for nvbench and use latest upstream.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.

### CODE REVIEW

**Comment by robertmaynard** [comment]
Currently manually verifing cudf

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
conda C++ tests will probably need to install `cuda-nvml-dev` for CUDA 12 to have the `nvml.h` header. Not sure about CUDA 11.

Is it expected that nvbench will always require nvml to build, going forward? This will impact build dependencies for cuDF and other libraries.

**Review by bdice — CHANGES_REQUESTED** [review]
Blocking until we can discuss the nvml.h dependency.

**Comment by robertmaynard** [comment]
> CI is failing because it can't resolve `#include <nvml.h>`. https://github.com/rapidsai/rapids-cmake/actions/runs/6879508245/job/18711836813?pr=488#step:7:2653
> 
> conda C++ tests will probably need to install `cuda-nvml-dev` for CUDA 12 to have the `nvml.h` header. Not sure about CUDA 11.
> 
> Is it expected that nvbench will always require nvml.h to build, going forward? This will impact build dependencies for cuDF and other libraries.

This in not desired behavior. I will open another PR on nvbench that ensure nvml is entirely optional

**Comment by robertmaynard** [comment]
Upstream fix to restore nvml to being an optional dependency: https://github.com/NVIDIA/nvbench/pull/149

**Review by bdice — APPROVED** [review]

**Pull request merged**
