### PR TITLE
Warn when override of a default package uses the incorrect case

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
It is a common mistake to presume that all entries in a package override json should use lower case names, since the vast majority of default packages are all lower case. This causes silent 'failures' when the override doesn't work.

We now normalize all package data internally so that  overrides for `ABC`, `abc`, and `Abc` all map to the same package. In addition we have added information tracking the proper name of bundled packages. This allows us to warn when an override uses the non correct package name, and treat it like the proper name.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.

### CODE REVIEW

**Comment by vyasr** [comment]
Do we need to put in some sort of check to avoid accidentally introducing name collisions if there really are two packages that only differ by capitalization? I don't think it's critical but IIUC this PR is going to make such cases collide unconditionally.

**Comment by robertmaynard** [comment]
> Do we need to put in some sort of check to avoid accidentally introducing name collisions if there really are two packages that only differ by capitalization? I don't think it's critical but IIUC this PR is going to make such cases collide unconditionally.

Do you mean when the package is listed twice in the defaults.json? The PR does warn if an override has a different case. 
Multiple overrides of the same package can't clash as only the first occurence of each package is read.

**Comment by vyasr** [comment]
Yes, I mean in defaults.json if there is a real CCCL and cccl package for example.

**Review by vyasr — APPROVED** [review]

**Pull request merged**
