### PR TITLE
Update cuco git tag to support `cuco::static_set`

### PR DESCRIPTION
**Pull request by PointKernel**
## Description
This PR fetches the latest cuco git tag which supports `cuco::static_set`.

https://github.com/rapidsai/cudf/pull/13261 confirmed the update won't break cudf.

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

### CODE REVIEW

**Comment by robertmaynard** [comment]
This looks good, will want to test.

While I do that, can you bump the rapids-cmake version used by cuCollections to 23.06?

**Comment by PointKernel** [comment]
Opened https://github.com/NVIDIA/cuCollections/pull/302

**Review by robertmaynard — APPROVED** [review]
Approving, would like to move the SHA1 once https://github.com/NVIDIA/cuCollections/pull/302 has been merged.

**Comment by PointKernel** [comment]
cuco SHA updated.

**Pull request merged**
