### PR TITLE
Update cuco to version that supports Ada and Hopper

### PR DESCRIPTION
**Pull request by robertmaynard**
## Description
Update cuco version to one that supports Ada and Hopper ( by using rapids-cmake 22.12 )

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.

### CODE REVIEW

**Review by vyasr — APPROVED** [review]

**Review by bdice — APPROVED** [review]

**Comment by vyasr** [comment]
Let's wait to merge this until Monday morning just in case. I don't want some unexpected change to suddenly block the hotfix releases that are ongoing to break builds for people who want to work on something over the weekend.

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by robertmaynard** [comment]
@gpucibot merge

**Comment by robertmaynard** [comment]
@gpucibot merge

**Pull request merged**
