### PR TITLE
Update cuco git tag

### PR DESCRIPTION
**Pull request by sleeepyjack**
## Description
This PR updates the version of cuCollections to include a bugfix that is needed for G+H bringup.

Test PRs in downstream projects:
- [x] rapidsai/cudf#14306
- [x] rapidsai/cugraph#3946
- [x] rapidsai/cuml#5626 -> Python tests are failing for some (maybe unrelated) reason but cpp tests run fine
- [x] rapidsai/raft#1917
- … can someone come up with other projects that use cuco

## Checklist
- [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/rapids-cmake/blob/HEAD/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [x] The `cmake-format.json` is up to date with these changes.
- [ ] I have added new files under rapids-cmake/
   - [ ] I have added include guards (`include_guard(GLOBAL)`)
   - [ ] I have added the associated docs/ rst file and update the api.rst

CC @PointKernel

### CODE REVIEW

**Comment by robertmaynard** [comment]
Thank you for creating the test PR's on other projects.

This looks good, just say when you want it merged and we will do it.

**Review by robertmaynard — APPROVED** [review]

**Comment by sleeepyjack** [comment]
@robertmaynard Thanks!
I just checked the Python test errors in the downstream PRs. All of them seem to be unrelated to the cuco update. If you can confirm that this is expected behavior, we can merge this PR.

**Comment by robertmaynard** [comment]
> @robertmaynard Thanks! I just checked the Python test errors in the downstream PRs. All of them seem to be unrelated to the cuco update. If you can confirm that this is expected behavior, we can merge this PR.

Those failures look to be related to the known arrow / aws sdk issue that the cudf team is fixing

**Pull request merged**
